apiVersion: networking.k8s.io/v1beta1
kind: Ingress
spec:
  rules:
    - http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              serviceName: hello-k8s
              servicePort: 8080