spec:
  rules:
    - http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              serviceName: hello-k8s
              servicePort: 80
          - path: /v3/api-docs
              pathType: Prefix
              backend:
                serviceName: hello-k8s
                servicePort: 80